### ISSUE TITLE
QMK console never detects other half

### ISSUE THREAD

**Issue by drlkf** [dlip/harite#3]
Hi! It's me again :)

I've ordered my parts and started soldering, but I'm having trouble connecting the two parts. I have done the following:

- Soldered each RPI2040 and flashed them with their respective half firmware
- Soldered both USB-C ports to the PCBs and made sure the pin pairs respond according to the guide
- I also checked continuity between the USB-C pins and their connected pin on each RPI, they all respond as expected

But when I start the QMK console, it produces the `slave_matrix` error indefinitely like so:

```
Ψ Console Connected: Dane Lipscombe harite (FEED:0000:1)
Dane Lipscombe:harite:1: Failed to execute slave_matrix
Dane Lipscombe:harite:1: Target disconnected, throttling connection attempts
Dane Lipscombe:harite:1: Failed to execute slave_matrix
Dane Lipscombe:harite:1: Target disconnected, throttling connection attempts
```

I've tried plugging both halves and they produce the same behavior. I don't really know what to check at this point, could it be the USB-C cable that is poor quality? I'm using a cheap 60W cable from AliExpress, tried 2 of them that work find with my phone, should I try a specific brand? If it isn't the cable, could you give any pointers on what to check?

Thank you!

**Comment by dlip** [comment]
Hi @drlkf,
I don't think it would be the cable, even cheap ones are decent quality these days. Though you could do a continuity check between the halves. The A, B, C, D pairs should connect to the same ones on the other side and no other pins.

**Comment by drlkf** [comment]
Indeed, I found my connectivity issue doing this. Thanks!
